-- DATABASE SETUP SCRIPT

CREATE TABLE IF NOT EXISTS trainings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    longDescription TEXT,
    icon VARCHAR(100),
    image TEXT,
    modules JSON
);

CREATE TABLE IF NOT EXISTS services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    icon VARCHAR(100),
    image TEXT,
    secondaryImage TEXT,
    shortDescription TEXT,
    fullDescription TEXT,
    benefits JSON,
    process JSON
);

CREATE TABLE IF NOT EXISTS industries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    image TEXT,
    secondaryImage TEXT,
    icon VARCHAR(100),
    info TEXT,
    overview TEXT,
    segments JSON,
    solutions JSON,
    insights JSON,
    edge JSON
);

-- Internal Management Tables (Private)

CREATE TABLE IF NOT EXISTS inquiries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    mobile VARCHAR(20) NOT NULL,
    message TEXT,
    service VARCHAR(255),
    source VARCHAR(50) DEFAULT 'Website',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trainers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mobile VARCHAR(20),
    email VARCHAR(255),
    expertise VARCHAR(255),
    details JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS licenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    license_number VARCHAR(255),
    start_date DATE,
    end_date DATE,
    status VARCHAR(50) DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO trainings (slug, title, description, longDescription, icon, image, modules) VALUES ('it-training', 'IT Training', 'Master modern technologies with our comprehensive IT training programs.', 'Our IT Training programs are designed to equip you with the latest skills in the tech industry. Whether you are a beginner looking to start a career in coding or a professional aiming to upskill, our expert-led courses cover everything from foundational programming to advanced cloud computing and data science.', 'Laptop', 'https://img.freepik.com/free-photo/team-database-admins-analyzing-source-code-wall-screen-tv-comparing-errors-using-digital-tablet-busy-server-room-two-cloud-programers-debugging-algorithm-software-innovation-office_482257-43976.jpg', '["Software Development","Web Development","Data Science","Cloud Computing","Cybersecurity Basics","DevOps Engineering","Mobile App Development","AI & Machine Learning"]');
INSERT INTO trainings (slug, title, description, longDescription, icon, image, modules) VALUES ('general-training', 'General Trainings', 'Comprehensive professional development and competitive exam preparation.', 'Boost your career prospects with our General Training programs. specialized in competitive exam preparation for government jobs and professional skills development to enhance your workplace effectiveness.', 'BookOpen', 'https://img.freepik.com/free-photo/business-startup-strategy-goals-concept_53876-120909.jpg', '["Government Jobs Preparation","Professional Skills Development","Communication Skills","Leadership & Management","Time Management","Critical Thinking","Interview Preparation"]');
INSERT INTO trainings (slug, title, description, longDescription, icon, image, modules) VALUES ('ehs-training', 'EHS Training', 'Essential Environment, Health, and Safety training for a secure workplace.', 'Safety is paramount in any industry. Our EHS (Environment, Health, and Safety) training ensures your workforce is compliant, safe, and prepared for emergencies. We cover international safety standards and practical emergency response techniques.', 'ShieldCheck', 'https://img.freepik.com/free-photo/female-construction-engineers-working-together-discussing-project-plan_114579-14641.jpg', '["Safety Training","Safety, Fire Extinguisher, CPR","Workplace Hazard Identification","First Aid Certification","Industrial Safety Protocols","Environmental Compliance"]');
INSERT INTO trainings (slug, title, description, longDescription, icon, image, modules) VALUES ('kids-language', 'Kids & Language', 'Foundational courses in public speaking, phonics, and creative skills.', 'Nurture your child''s potential with our specialized courses for kids. We focus on building confidence, creativity, and strong communication skills from an early age through interactive and engaging learning methods.', 'Gamepad2', 'https://img.freepik.com/free-photo/cute-girl-writing-notes-while-elearning-laptop-home_637285-9354.jpg', '["Public Speaking & Creative Writing","Phonics","Mathematical Ability","Logic & Reasoning","Language Learning (Basics)","Art & Creativity Workshop"]');
INSERT INTO trainings (slug, title, description, longDescription, icon, image, modules) VALUES ('fd', 'sfdsd', 'sdf', 'dsf', 'Laptop', '', '["sdf","sdf"]');

INSERT INTO services (slug, title, icon, image, secondaryImage, shortDescription, fullDescription, benefits, process) VALUES ('permanent-staffing', 'Permanent Hiring', 'Users', 'https://img.freepik.com/free-photo/smiling-young-couple-shaking-hands-with-insurance-agent_1139-978.jpg?w=740', 'https://img.freepik.com/free-photo/businesspeople-working-finance-accounting-office_23-2148908915.jpg?w=740', 'We help organizations hire expert full-time talent across IT and Non-IT roles using creative sourcing strategies.', 'In today''s highly competitive market, finding the right permanent talent is the bedrock of organizational stability and long-term innovation. At TRYITTECH LLP, we don''t just fill vacancies; we build your core workforce. We specialize in identifying high-caliber professionals for both IT and Non-IT roles, ensuring they align perfectly with your technical requirements and corporate culture.

Our methodology is rigorous and data-driven. We leverage a proprietary database of millions of pre-screened professionals and employ multi-channel sourcing—including social recruitment and passive candidate headhunting—to find the 10% of talent that truly drives business outcomes. From executive leadership to specialized technical contributors, our permanent staffing models are designed to reduce turnover and maximize ROI.', '["Access to a proprietary database of over 1M pre-screened professionals.","Reduced time-to-hire by 40% through specialized sourcing workflows.","In-depth cultural fit & behavioral assessment to ensure 95%+ retention.","90-day replacement guarantee providing risk-free hiring confidence.","Dedicated account managers specializing in your specific industry vertical."]', '["Requirement Analysis","Strategic Sourcing","Technical Vetting","Client Interviews","Onboarding Support"]');
INSERT INTO services (slug, title, icon, image, secondaryImage, shortDescription, fullDescription, benefits, process) VALUES ('contract-staffing', 'Contract Staffing', 'ClipboardCheck', 'https://img.freepik.com/premium-photo/executives-shaking-hands-office_13339-73579.jpg?w=740', 'https://img.freepik.com/free-photo/diverse-business-people-office_53876-13350.jpg?w=740', 'Temporary staffing solutions enabling enterprises to focus on core business operations with strategic agility.', 'Operational agility is critical in the modern business landscape. Our contract staffing services empower your organization to respond rapidly to project-based demands, seasonal peaks, or specialized skill gaps without the long-term liabilities of permanent headcount.

We manage the entire lifecycle of your temporary workforce—from statutory compliance and payroll to benefits and offboarding. By acting as the Employer of Record (EOR), TRYITTECH LLP assumes the administrative burden, allowing your internal leadership to focus exclusively on project delivery. Our contract pool includes thousands of pre-vetted specialists in Java, Python, SAP, Cloud Architecture, and Executive Management, ready for immediate deployment.', '["Rapid scaling of technical teams to meet sudden project deadlines.","Elimination of administrative overhead and employee liability.","100% compliance with Indian labor laws (PF, ESI, Gratuity, PT).","Shorter hiring cycles with access to 50,000+ active contractors.","Flexible \"Contract-to-Hire\" models for evaluating potential before permanent offers."]', '["Resource Profiling","Vetting & Screening","Client Evaluation","Compliance Setup","Resource Deployment"]');
INSERT INTO services (slug, title, icon, image, secondaryImage, shortDescription, fullDescription, benefits, process) VALUES ('offshore-it-staffing', 'Offshore IT Hub', 'Globe', 'https://img.freepik.com/free-photo/business-team-boardroom-attend-videocall-meeting-with-investors-group-discussing-about_482257-133177.jpg?w=740', 'https://img.freepik.com/free-photo/software-developer-working-office_23-2148908906.jpg?w=740', 'Cost-effective offshore IT staffing solutions that save time, cost, and significant operational effort.', 'Unlock the massive potential of global talent with our Offshore IT Staffing solutions. India remains the world''s most sought-after destination for technical excellence, and TRYITTECH LLP provides the bridge to this elite talent pool. We help international businesses establish "Global Capability Centers" (GCCs) or specialized offshore teams in our Hyderabad hub.

Our model provides more than just developers; we provide a complete, secure infrastructure and a managed environment that acts as a seamless extension of your home office. By leveraging India''s time-zone advantages, we enable 24/7 development cycles, allowing your business to move faster while optimizing costs by up to 70% compared to Western markets.', '["30-70% reduction in total cost of ownership compared to US/EU hiring.","Access to India''s massive pool of 5M+ technical professionals.","Comprehensive IP protection and enterprise-grade security protocols.","Full management of Indian tax, labor law, and local compliance.","Overnight turnaround cycles with efficient 24/7 delivery frameworks."]', '["GCC Strategy","Infrastructure Setup","Talent Pod Building","Knowledge Transfer","Operational Scale"]');
INSERT INTO services (slug, title, icon, image, secondaryImage, shortDescription, fullDescription, benefits, process) VALUES ('staff-augmentation', 'Staff Augmentation', 'UserPlus', 'https://img.freepik.com/free-photo/close-up-company-team-working_23-2149114777.jpg?w=740', 'https://img.freepik.com/free-photo/colleagues-working-together-office_23-2148908918.jpg?w=740', 'Dedicated IT professionals and fully managed teams tailored to your specific technical business needs.', 'Bridge critical skill gaps instantly with Staff Augmentation. Unlike traditional hiring, Staff Augmentation allows you to inject specialized expertise directly into your internal teams for the exact duration you need it. Whether you''re missing a DevOps architect, a Data Scientist, or a Frontend specialist, we provide the talent while you retain full project control. Our augmented staff follows your processes, uses your tools, and reports to your managers—but TRYITTECH LLP handles the employment liablity, training, and benefits. This "Plug-and-Play" model accelerates your time-to-market while avoiding the long-term overheads of permanent hiring for project-specific needs.', '["Immediate access to niche skillsets (AI, Blockchain, SAP, Azure).","Zero recruitment costs and training overhead for your company.","Maintain 100% control over project direction and IP.","Highly flexible termination/scaling clauses for project-based work.","Seamless integration with internal Agile or DevOps cultures."]', '["Skill Mapping","Rapid Interviewing","Onboarding","Integration","Performance Management"]');
INSERT INTO services (slug, title, icon, image, secondaryImage, shortDescription, fullDescription, benefits, process) VALUES ('managed-rpo', 'RPO Frameworks', 'Briefcase', 'https://img.freepik.com/premium-photo/human-resources-talent-management-recruitment-business-concept_926199-2026683.jpg?w=740', 'https://img.freepik.com/free-photo/businesswoman-working-office_23-2148908902.jpg?w=740', 'Scalable talent acquisition models (Recruitment Process Outsourcing) that evolve with business growth.', 'Our Recruitment Process Outsourcing (RPO) is a strategic, long-term partnership where TRYITTECH LLP manages all or part of your recruitment lifecycle. We act as an extension of your company, using our specialized tools, employer branding expertise, and US-backed methodologies to build a high-performing talent pipeline. An RPO transformation isn''t just about rebuilding your hiring engine. We optimize your sourcing technologies, refine your candidate experience, and implement rigorous data analytics to drive down your cost-per-hire. Whether you need an End-to-End RPO, Project-based hiring, or Recruiters-on-Demand, we scale with your growth.', '["Lower cost-per-hire through optimized sourcing technologies.","Advanced AI-driven analytics for predicting hiring trends.","Enhanced employer brand through professional candidate experience.","Strategic scalability to manage massive hiring surges (100+ hires).","Improved quality of hire through multi-tiered assessment frameworks."]', '["Hiring Audit","Branding Strategy","Technology Integration","Candidate Pipeline Building","Full-Cycle Hiring"]');
INSERT INTO services (slug, title, icon, image, secondaryImage, shortDescription, fullDescription, benefits, process) VALUES ('payroll-services', 'Payroll Services', 'Banknote', 'https://img.freepik.com/free-photo/top-view-man-writing-something-paper-with-keyboard-eyeglasses-pen-cactus-magnifier-wooden-background-horizontal_176474-6280.jpg?w=740', 'https://img.freepik.com/free-photo/calculator-finance-accounting-concept_53876-121652.jpg?w=740', 'End-to-end payroll solutions for Indian businesses, ensuring compliance and operational excellence.', 'Managing payroll in India is a complex balancing act of local labor laws, tax codes, and statutory requirements. TRYITTECH LLP takes this burden off your shoulders, providing a zero-error, 100% compliant payroll engine. We handle everything from salary processing and PF/ESI calculations to professional tax and income tax filings. Our payroll solution is built on modern, secure, and cloud-based technology. We provide an Employee Self-Service (ESS) platform where your staff can access payslips and tax declarations effortlessly. By outsourcing your payroll to us, you eliminate administrative errors, ensure timely payments, and maintain perfect standing with all Indian regulatory bodies.', '["Zero-error salary processing with automated cloud workflows.","Full management of PF, ESI, Gratuity, LWF, and Professional Tax.","Secure Employee Self-Service (ESS) portal for pay and tax info.","Direct handling of all salary-related employee queries.","Comprehensive monthly and annual compliance reporting for audits."]', '["Policy Alignment","Employee Data Setup","Calculation & Processing","Statutory Filing","Query Management"]');

INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('it', 'Information Technology', 'https://innovasolutions.com/wp-content/uploads/2025/05/hitech-Pic.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_DPE_L1_B1_Desktop.jpg', 'Cpu', 'Innovative tech leadership search and digital transformation staffing.', 'The Information Technology sector is the backbone of modern global enterprises. At TRYITTECH LLP, we specialize in identifying and placing top-tier technical talent that drives innovation. From Cloud Architects to Cybersecurity Experts, we provide the human capital necessary to navigate the rapidly evolving digital landscape.', '[{"title":"Software Engineering","description":"Placing experts in Full Stack, Mobile, and Specialized Backend development."},{"title":"Cloud & Infrastructure","description":"Specialized talent for AWS, Azure, and Google Cloud ecosystems."},{"title":"Data Science & AI","description":"Hiring Ph.D. level researchers and experienced machine learning engineers."}]', '[{"title":"Digital Transformation Staffing","description":"Building teams to transition legacy systems to modern architectures."},{"title":"On-Demand Tech Scaling","description":"Rapidly deploying augmented teams for project-critical deadlines."}]', '[{"title":"The Future of AI in Enterprise","category":"Technology","image":"https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80"},{"title":"Cloud Migration Strategies for 2026","category":"Cloud","image":"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80"}]', '[{"title":"Agile Delivery","description":"Faster time-to-market with our rapid deployment models.","icon":"Zap"},{"title":"Tech Excellence","description":"Access to the top 1% of specialized technical talent.","icon":"Target"},{"title":"Global Grid","description":"24/7 follow-the-sun delivery model for unified support.","icon":"Globe"},{"title":"Strategic Scale","description":"Ability to scale teams from 5 to 500 within weeks.","icon":"BarChart3"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('healthcare', 'Healthcare', 'https://innovasolutions.com/wp-content/uploads/2025/05/Health-Lifescience-Pic.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_TAL_L2_B1_Desktop-2.jpg', 'HeartPulse', 'Specialized medical talent acquisition and healthcare IT solutions.', 'Healthcare is undergoing a massive digital shift. We bridge the gap between medical expertise and technological efficiency. Our talent network includes specialized healthcare IT professionals, clinical researchers, and administrative leadership that understands the nuances of patient care and regulatory compliance.', '[{"title":"HealthTech","description":"Experts in Electronic Health Records (EHR) and telehealth platforms."},{"title":"BioTech","description":"Staffing for laboratory research and development phases."},{"title":"Clinical Staffing","description":"Specialized placement for nursing, therapy, and clinical management."}]', '[{"title":"Regulatory Compliance Teams","description":"Building teams focused on HIPAA and GDPR healthcare standards."},{"title":"Medical Research Augmentation","description":"Scalable research teams for clinical trials."}]', '[{"title":"Telehealth Evolution","category":"Healthcare","image":"https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80"},{"title":"AI in Drug Discovery","category":"Life Sciences","image":"https://images.unsplash.com/photo-1532187863486-abf51ad9869d?w=800&q=80"}]', '[{"title":"HIPAA Ready","description":"Full compliance with international medical data standards.","icon":"Shield"},{"title":"Clinical Speed","description":"Accelerate R&D phases with specialized medical talent.","icon":"Zap"},{"title":"Patient Centric","description":"Solutions designed with patient outcomes at the core.","icon":"Users"},{"title":"Innovation DNA","description":"Integrating future-tech into legacy medical systems.","icon":"Lightbulb"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('bfsi', 'BFSI', 'https://innovasolutions.com/wp-content/uploads/2025/05/Banking-secor.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_DA_L1_B1_Desktop.jpg', 'Building2', 'Secure banking and finance staffing for the digital economy.', 'In the Banking, Financial Services, and Insurance (BFSI) sector, security and precision are paramount. We provide professionals who understand the complexities of Fintech, High-Frequency Trading, and risk management. Our candidates bring both technical prowess and deep domain knowledge of global financial regulations.', '[{"title":"Fintech","description":"Innovative talent for payment gateways and blockchain-based finance."},{"title":"Investment Banking","description":"Quantitative analysts and high-speed trading system developers."},{"title":"Insurance Technology","description":"Modernizing claims processing and risk assessment through technology."}]', '[{"title":"Security-First Staffing","description":"Placing cybersecurity experts with deep financial sector experience."},{"title":"Compliance Modernization","description":"Teams focused on automating regulatory reporting and transparency."}]', '[{"title":"Digital Banking Trends","category":"Fintech","image":"https://images.unsplash.com/photo-1550565118-3a14e8d0386f?w=800&q=80"},{"title":"Cybersecurity in Finance","category":"Security","image":"https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80"}]', '[{"title":"Risk Mitigated","description":"Rigorous vetting for security-cleared financial talent.","icon":"Shield"},{"title":"Fintech Fluent","description":"Deep understanding of modern digital payment ecosystems.","icon":"Zap"},{"title":"Legacy Bridge","description":"Seamlessly migrating core banking to the cloud.","icon":"BarChart3"},{"title":"Compliance Lead","description":"Staying ahead of evolving global finance regulations.","icon":"Award"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('automotive', 'Automotive', 'https://innovasolutions.com/wp-content/uploads/2025/05/manufacturi-Pic.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/cloud-infrastructure.jpg', 'Car', 'Driving automotive excellence through advanced manufacturing talent.', 'The automotive industry is being redefined by electrification and autonomous systems. TRYITTECH LLP provides the specialized engineering talent required for the next generation of mobility. From hardware engineers for EV batteries to software developers for ADAS systems, we power the future of transportation.', '[{"title":"Electric Vehicles","description":"Engineers specializing in battery chemistry and power electronics."},{"title":"Autonomous Driving","description":"Computer vision and sensor fusion experts."},{"title":"Smart Manufacturing","description":"IoT and robotics specialists for the assembly floor."}]', '[{"title":"EV R&D Teams","description":"Complete research teams for breakthrough mobility technologies."},{"title":"Supply Chain Optimization","description":"Strategic staffing for automotive logistics and procurement."}]', '[{"title":"The EV Revolution","category":"Automotive","image":"https://images.unsplash.com/photo-1593941707882-a5bba149a4f4?w=800&q=80"},{"title":"Autonomous AI Safety","category":"AI","image":"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80"}]', '[{"title":"Industry 4.0","description":"Leaders in smart factory staffing and automation.","icon":"Factory"},{"title":"Mobility First","description":"Experts in future-mobility and autonomous software.","icon":"Zap"},{"title":"Supply Expert","description":"Deep visibility into automotive supply chain talent.","icon":"Target"},{"title":"Global Grid","description":"24/7 follow-the-sun delivery model for unified support.","icon":"Globe"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('logistics', 'Logistics', 'https://innovasolutions.com/wp-content/uploads/2025/05/travel-Transpost-Pic.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/06/Cloud-Services-thumb-1.jpg', 'Truck', 'Optimizing supply chain talent for global trade and local delivery.', 'Logistics and supply chain management are more complex than ever. We provide the strategic thinkers and operational experts who keep the world moving. Our candidates specialize in last-mile delivery technology, warehousing automation, and global trade compliance.', '[{"title":"Supply Chain Strategy","description":"Analysts and managers for global shipment optimization."},{"title":"Warehouse Automation","description":"Robotics and software experts for modern fulfillment centers."},{"title":"Freight Tech","description":"Developing platforms for real-time tracking and logistics transparency."}]', '[{"title":"Last-Mile Efficiency Teams","description":"Specialized talent for urban delivery and route optimization."},{"title":"Inventory Resilience Planning","description":"Staffing for risk management and supply continuity."}]', '[{"title":"Last-Mile Delivery Tech","category":"Logistics","image":"https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80"},{"title":"Automated Fulfillment","category":"Automation","image":"https://images.unsplash.com/photo-1566576721346-d4a3b4eaad54?w=800&q=80"}]', '[{"title":"Real-time Talent","description":"Staffing for real-time logistics tracking systems.","icon":"Zap"},{"title":"Global Reach","description":"Connecting talent across major global trade hubs.","icon":"Globe"},{"title":"Tech Optimized","description":"Experts in modern warehouse management software (WMS).","icon":"BarChart3"},{"title":"Agile Scale","description":"Rapid scaling for peak seasonal demand cycles.","icon":"Users"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('non-it', 'Non-IT Professional', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_TAL_L2_B1_Desktop-2.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/find-a-job-strip-nbg.jpg', 'Briefcase', 'Diverse professional staffing solutions across leadership and management.', 'Excellence in leadership and administration is industry-agnostic. At TRYITTECH LLP, we source high-impact professionals for roles in Finance, HR, Marketing, and Operations. Our holistic approach ensures that non-technical leadership is just as robust as your engineering teams.', '[{"title":"Executive Leadership","description":"Placing C-level and senior management professionals."},{"title":"Operations Management","description":"Specialized talent for organizational efficiency and growth."},{"title":"Corporate Services","description":"HR, Finance, and Administrative staffing for office excellence."}]', '[{"title":"Global Talent Pipeline","description":"Connecting enterprises with international leadership talent."},{"title":"Diversity & Inclusion Hiring","description":"Focused strategies for building balanced and inclusive teams."}]', '[{"title":"Leadership in Digital Era","category":"Management","image":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80"},{"title":"The Future of Remote Work","category":"HR","image":"https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&q=80"}]', '[{"title":"Strategic Match","description":"AI-driven leadership matching for cultural fit.","icon":"Target"},{"title":"Speed to Hire","description":"Executive placements in average of 21 days.","icon":"Zap"},{"title":"Holistic Vetting","description":"Beyond credentials: EQ and cultural alignment assessment.","icon":"Users"},{"title":"Global Pool","description":"Access to passive candidates across 40+ countries.","icon":"Globe"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('retail', 'Retail & E-commerce', 'https://innovasolutions.com/wp-content/uploads/2025/05/retail-CPG-Pic.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_TAL_L2_B1_Desktop-2.jpg', 'ShoppingBag', 'Customer-centric retail staffing and e-commerce technology talent.', 'The retail landscape is merging physical and digital experiences. We provide the expertise to manage omnichannel platforms, inventory systems, and customer-facing technology. Our candidates help retailers stay competitive in an era of instant delivery and personalized shopping.', '[{"title":"Omnichannel Retail","description":"Staffing for seamless online and offline customer journeys."},{"title":"E-commerce Platforms","description":"Experts in Shopify, Magento, and custom headless commerce."},{"title":"Retail Analytics","description":"Data scientists focused on consumer behavior and trend forecasting."}]', '[{"title":"Holiday Peak Scaling","description":"Rapid staffing for peak seasonal demand in retail and logistics."},{"title":"Digital Storefront Modernization","description":"Building tech teams to upgrade legacy retail systems."}]', '[{"title":"Omnichannel Mastery","category":"Retail","image":"https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80"},{"title":"Personalized Shopping AI","category":"AI","image":"https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80"}]', '[{"title":"Customer First","description":"Focused on CX specialist talent acquisition.","icon":"Users"},{"title":"Platform Pro","description":"Deep bench of platform-specific engineering talent.","icon":"Zap"},{"title":"Omni Vision","description":"Unified talent for online and physical retail.","icon":"Target"},{"title":"Scalable Force","description":"Flexible workforce for high-demand retail events.","icon":"BarChart3"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('telecom', 'Telecom & Networking', 'https://innovasolutions.com/wp-content/uploads/2025/05/Comm-media-Pic-1.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_DA_L1_B1_Desktop.jpg', 'Radio', 'Next-gen network solutions and 5G infrastructure engineering talent.', 'Connectivity is the lifeblood of the modern world. We support the telecommunications industry by providing engineers and architects who build 5G, fiber optic networks, and satellite communications. Our talent powers the infrastructure that connects billions of devices.', '[{"title":"5G Infrastructure","description":"Specialists in small cell deployment and core network upgrades."},{"title":"Network Security","description":"Architects focused on protecting national and enterprise communication grids."},{"title":"Satellite Comms","description":"Aerospace and telecom combined expertise for global connectivity."}]', '[{"title":"Broadband Expansion Teams","description":"Project-based staffing for large-scale fiber and wireless rollouts."},{"title":"Managed Network Operations","description":"Placing NOC and field engineers for 24/7 reliability."}]', '[{"title":"The 5G Future","category":"Telecom","image":"https://images.unsplash.com/photo-1562408590-e32931084e23?w=800&q=80"},{"title":"Securing Next-Gen Networks","category":"Security","image":"https://images.unsplash.com/photo-1558494949-ef010958a196?w=800&q=80"}]', '[{"title":"5G Pioneers","description":"Access to early-adopter 5G engineering talent.","icon":"Zap"},{"title":"Network First","description":"Focus on high-availability networking experts.","icon":"Shield"},{"title":"Satellite Bench","description":"Rare aerospace communications talent network.","icon":"Target"},{"title":"Always On","description":"NOC teams for mission-critical connectivity.","icon":"Globe"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('manufacturing', 'Manufacturing', 'https://innovasolutions.com/wp-content/uploads/2025/05/manufacturi-Pic.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/cloud-infrastructure.jpg', 'Factory', 'Industrial growth through advanced talent and Industry 4.0 expertise.', 'Manufacturing is entering the Industry 4.0 era. We provide the mechanical engineers, automation specialists, and IoT experts who make factories smarter and more efficient. Our candidates help industrial leaders integrate robotics and AI into traditional production lines.', '[{"title":"Industrial Automation","description":"PLC programming and robotics maintenance specialists."},{"title":"Smart Factory IoT","description":"Placing sensors and software experts for real-time plant monitoring."},{"title":"Quality & Six Sigma","description":"Operational excellence leads for manufacturing precision."}]', '[{"title":"Plant Modernization Teams","description":"Engineering talent to oversee the transition to smart manufacturing."},{"title":"Global SCM Support","description":"Staffing for international procurement and vendor management."}]', '[{"title":"Smart Factory Trends","category":"Industry 4.0","image":"https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80"},{"title":"Robotics in Production","category":"Automation","image":"https://images.unsplash.com/photo-1518314916381-77a37c2a49ae?w=800&q=80"}]', '[{"title":"Automation DNA","description":"Experts in integrating robots with human talent.","icon":"Factory"},{"title":"Precision Hires","description":"Rigorous testing for high-precision engineering roles.","icon":"Target"},{"title":"Safety Focused","description":"Full safety-certified workforce for industrial zones.","icon":"Shield"},{"title":"Modern Vision","description":"Bridging OT and IT for unified smart production.","icon":"Zap"}]');
INSERT INTO industries (slug, name, image, secondaryImage, icon, info, overview, segments, solutions, insights, edge) VALUES ('bpo', 'BPO Services', 'https://innovasolutions.com/wp-content/uploads/2025/06/Cloud-Services-thumb-1.jpg', 'https://innovasolutions.com/wp-content/uploads/2025/03/SOL_TAL_L2_B1_Desktop-2.jpg', 'Headphones', 'Efficiency-driven outsourcing talent for global business processing.', 'Global business processing relies on high-quality operations. We provide the team leads, language experts, and technical support professionals who ensure seamless BPO delivery. Our focus is on high-value BPO roles that require specialized domain knowledge.', '[{"title":"Technical Support","description":"Tier 1 to Tier 3 support experts for global software firms."},{"title":"Financial Processing","description":"Staffing for specialized accounting and audit outsourcing."},{"title":"Customer Experience","description":"Multilingual professionals for superior global client engagement."}]', '[{"title":"Multilingual Hub Setup","description":"Building teams with uncommon language fluencies for specific markets."},{"title":"Process Optimization Leads","description":"Hiring consultants to automate and streamline BPO workflows."}]', '[{"title":"The Future of BPO","category":"Operations","image":"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80"},{"title":"Multilingual Support Success","category":"CX","image":"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80"}]', '[{"title":"Polyglot Talent","description":"Support in 40+ languages for a global clientele.","icon":"Globe"},{"title":"Tech Stack Savvy","description":"Deep knowledge of Zendesk, Salesforce, and modern CRM.","icon":"Zap"},{"title":"Quality Assurance","description":"Dedicated QA leads for every single client account.","icon":"Award"},{"title":"Scalable Hubs","description":"Expanding support teams from 10 to 100 within days.","icon":"Users"}]');
